services:
  - type: web
    name: pana-backend
    env: node
    region: ohio
    plan: free
    buildCommand: cd backend/server && npm install && npx tsc
    startCommand: cd backend/server && node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: ./service-account.json
      - key: NODE_VERSION
        value: 18
